### ISSUE TITLE
Can not load the tokenizer.

### ISSUE THREAD

**Issue by Tianhang-Lyu** [vandijklab/cell2sentence-ft#4]
Hello! Dear cell2sentence developers. The peoject is excellent！
However, I encounted an issue, which I can not load the tokenizer while can normally load the model. The screen below show this issue. I really hope your response on this issue and maybe a helpful documentation will help us to learn this package.
![image](https://github.com/vandijklab/cell2sentence-ft/assets/144881393/3d5ce961-3341-440d-88c3-513a66a0f002)
![image](https://github.com/vandijklab/cell2sentence-ft/assets/144881393/2b11e6ff-b1de-407a-a16e-3b3178de3b45)

**Comment by sachalevy** [comment]
Hi @Tianhang-Lyu ,

Thanks for your interest in cell2sentence!

It seems like you're passing your model path to the `transformers.AutoTokenizer.from_pretrained` method. Since we're only fine-tuning the model, we do not edit the tokenizer. You should be able to load it directly by passing the name of the model to the `from_pretrained` function.

In short, you can swap `pretrained_model_name_or_path` with the name of the model like `"gpt2"`.

I hope this is helpful! Let me know if you have any other questions.
